* QADS
** About
QADS stands for 'Quick And Dirty Scripts'. It is a directory with small bash scripts I have made throughout the years that make my life easier. Some are very specific to my use cases, but some might be benificial for other people as well.

* Scripts
** htbscript
*** What does it do?
This script creates a folder inside a set HTB directory in which it will automate the first steps of hacking a HTB machine. It will save nmap results and add machines to the /etc/hosts file if needed with 'hed'.

*** Requirements
https://github.com/credmp/hed

** fauxmd
*** What does it do?
This script is used to interact with a visible shell prompt on a remote machine. Normally when using commands over ssh, you can only see the output of that command in the output of the ssh session, but not on the remote machine. This is logical, since most machines that you can access through ssh are headless servers. In my case however I have ssh access to an old monitor with a visible terminal on display. This script makes it possible to display the sent commands on the terminal through a faux command prompt that sends the users input to a screen session.

*** Requirements
For this script to work the user should have the program 'screen' installed on the remote machine and have a session running named 'session'. Also the user should have passworless access to the remote machine over ssh (through ssh-keys for example).

In order to be able to connect to the remote machine the following command should be ran first on the remote machine:

#+begin_src bash
screen -S session /bin/bash
#+end_src

Also make sure to set the target_machine variable in the script.

** notesearch
*** What does it do?
It searches for lines inside (org-)files inside a specified directory and outputs those lines with a whitespace between them so they can be used with other commands. This is useful if you have a lot of notes or other specific files inside a directory that you need to search inside of for a specific line.

The script can be used as follows:

#+begin_src bash
notesearch "desired match"
echo "desired match" | notesearch
#+end_src

Make sure to change the note_directory to the directory you want to search inside of.
You can also modify the file type to search for other files like markdown files or txt files.

** fnotesearch
*** What does it do?
The same as notesearch except fuzzy and with two optional flags:

The -f flag makes it so if a match is found, the entire content of the file is printed in terminal.
The -t flag adds the title of the org file in front of the output so it's easier to find with org-roam.

** dockcheck
*** What does it do?
It checks how many displays are connected and sets the corresponding xrandr output settings. As everyones setup is different this script requires quite a bit of modifying, but it's very useful if you have a setup in which you frequently switch between one and multiple screens (for example when using a docking station).
It also sets a specific wallpaper for each of the two possible conditions. These lines can be removed if desired.

** urlripper
*** What does it do?
It downloads mp3's that are specified in a file with yt-dlp. This is incredibly useful if you want to quickly rip a large set of your favourite royalty free songs straight from YouTube. Simply put each of the url's on a seperate line in a file and run.

*** Requirements
This script needs yt-dlp to run so check [[https://github.com/yt-dlp/yt-dlp][their repo]] for installation instructions.

** openai_grammar
*** What does it do?
It takes the content of a file and corrects its grammar based on the instructions in the prompt. The current prompt does it for the Dutch language. The prompt inside the script can obviously be edited to serve other needs as well.

*** Requirements
This requires [[https://github.com/LevitatingBusinessMan/openai-cli][LevitatingBusinessMan's 'openai-cli']] which requires an API-Key.

** ORUI-reload
*** What does it do?
It sends the f5 command to a program with the name ORUI in order to be able to use this in macro's.

** Propomo
*** What does it do?
It starts a 3 minute timer in which the user is expected to work. After the 3 minutes are over, the user is prompted with a zenity window and asked how that session went. Based on the users chosen level of focus, a break is started and after that a new work session begins, with the goal of eventually reaching flow. All of this is logged for analysis purposes.

* Scripts that should be aliasses
** dailywords
*** What does it do?
It counts the words in a file with the current date in the format YYYY-mm-dd.org. This is very useful if you have a daily notes file with this format that you want to track. It is useful if you want to use that daily word count for other operations like a polybar module or some sort of productivity contraption.

** headset
*** What does it do?
It connects to a specific bluetooth device specified by 'bluetooth_mac_address'. It is quite nice if your bluetooth device has problems autoconnecting with your machine so you can force it to do so.

** ipchecker
*** What does it do?
It checks the host IP in a specified order to easily display the relevant IP in a polybar script. If a user is connected to a tunnel (like in a hack the box scenario) this will be the default IP shown, otherwise it will show the wlan or eth IP.

** undock
*** What does it do?
After removing a laptop from its docking station it can be ran to turn on the disabled display if it has been turned off by 'dockcheck'
