#!/bin/bash

monitors=$(xrandr | grep -sw 'connected' | wc -l)

if [[ $monitors -ge 3 ]]; then
	xrandr --output eDP-1 --off
	xrandr --output DP-2-1 --rotate left --left-of DP-1 --primary
	nitrogen --restore
else
    feh --bg-scale /usr/share/backgrounds/i3/wall.png
fi
